from app.processing.comparison import compare_metrics


def _metrics(dataset) -> dict:
    return getattr(dataset, "metrics_json", None) or {}


def summarize_health(metrics: dict) -> dict:
    cover = metrics.get("cover", {}) or {}
    health = metrics.get("health", {}) or {}
    coral = float(cover.get("coral", 0) or 0)
    healthy = float(health.get("healthy", 0) or 0)
    bleached = float(health.get("bleached", 0) or 0)
    diseased = float(health.get("diseased", 0) or 0)
    risk = "low" if bleached + diseased < 18 else "moderate" if bleached + diseased < 32 else "elevated"
    return {"coral_cover": coral, "healthy": healthy, "bleached": bleached, "diseased": diseased, "risk_level": risk}


def summarize_temporal_change(metrics_a: dict, metrics_b: dict) -> dict:
    return compare_metrics(metrics_a or {}, metrics_b or {})


def build_reef_report_payload(dataset, comparison_dataset=None) -> dict:
    metrics = _metrics(dataset)
    health = summarize_health(metrics)
    ai = metrics.get("ai", {}) or {}
    temporal = None
    if comparison_dataset is not None:
        temporal = summarize_temporal_change(_metrics(comparison_dataset), metrics)
    report = {
        "executive_summary": f"AI analysis for {dataset.name} estimates {health['coral_cover']:.1f}% coral cover and a {health['risk_level']} reef-health risk profile.",
        "coral_cover_overview": f"Benthic cover classes indicate coral {health['coral_cover']:.1f}%, rock {(metrics.get('cover') or {}).get('rock', 0):.1f}%, sand {(metrics.get('cover') or {}).get('sand', 0):.1f}% and algae {(metrics.get('cover') or {}).get('algae', 0):.1f}%.",
        "reef_health_assessment": f"Health classes show healthy {health['healthy']:.1f}%, bleached {health['bleached']:.1f}% and diseased {health['diseased']:.1f}% signals in the processed metrics.",
        "risk_indicators": [
            "Moderate bleaching signal" if health["bleached"] >= 12 else "Low bleaching signal",
            "Localized disease-like class present" if health["diseased"] >= 8 else "Disease-like signal limited",
        ],
        "rugosity_and_habitat": f"Rugosity is {float(metrics.get('rugosity', 0) or 0):.3f}, indicating habitat complexity derived from the bathymetry grid.",
        "temporal_change": temporal or "No second dataset selected. Temporal comparison can be generated by selecting another processed survey.",
        "data_quality_notes": ai.get("image_quality", {}).get("notes", ["Quality metrics available"]),
        "limitations": "This automated report is generated from processed survey metrics and should be reviewed by a reef scientist before operational use.",
    }
    return {"dataset_id": dataset.id, "comparison_dataset_id": getattr(comparison_dataset, "id", None), "agent": "Scientific Report Agent", "status": "active", "report": report}


def generate_reef_report(dataset, comparison_dataset=None) -> dict:
    return build_reef_report_payload(dataset, comparison_dataset)


def answer_reef_question(dataset, question: str, comparison_dataset=None) -> dict:
    metrics = _metrics(dataset)
    health = summarize_health(metrics)
    q = (question or "").lower()
    answer = f"This reef appears to have a {health['risk_level']} risk profile, with {health['healthy']:.1f}% healthy coral class and {health['coral_cover']:.1f}% coral cover."
    if "bleach" in q:
        answer = f"The synthetic metrics show {health['bleached']:.1f}% bleaching-like class. This signal should be reviewed together with the original imagery and annotations."
    elif "increase" in q or "decrease" in q or "change" in q or "cover" in q:
        if comparison_dataset is not None:
            change = summarize_temporal_change(_metrics(comparison_dataset), metrics)
            coral_delta = change.get("coral_cover_change", {}).get("coral", 0)
            direction = "increased" if coral_delta > 0 else "decreased" if coral_delta < 0 else "remained stable"
            answer = f"Compared with the selected baseline, coral cover {direction} by {abs(coral_delta):.1f} percentage points in the processed metrics."
        else:
            answer = f"Current coral cover is {health['coral_cover']:.1f}%. Select a second dataset to compute temporal change."
    elif "quality" in q or "scientific" in q:
        answer = "The dataset is suitable for workflow validation, but not for scientific conclusions without expert review and field calibration."
    elif "risk" in q:
        answer = f"Main risks are bleaching ({health['bleached']:.1f}%) and disease-like class ({health['diseased']:.1f}%)."
    return {
        "dataset_id": dataset.id,
        "agent": "ReefQA Agent",
        "question": question,
        "answer": answer,
        "evidence": {
            "coral_cover": health["coral_cover"],
            "healthy": health["healthy"],
            "bleached": health["bleached"],
            "diseased": health["diseased"],
            "rugosity": metrics.get("rugosity"),
        },
        "disclaimer": "Automated answer generated from processed survey metrics.",
    }
